#!/usr/bin/env php
<?php
use Essentio\Core\Application;

require_once __DIR__ . "/vendor/autoload.php";
Application::cli(__DIR__);
require_once base_path("bootstrap.php");

// php cli greet -> Hello, You
// php cli greet --name NAME -> Hello, NAME
command("greet", fn() => error_log(sprintf("Hello, %s", arg("name") ?? "You")));

